### ISSUE TITLE
Bàn về câu nói của bản thân

### ISSUE THREAD

**Issue by nlphuog** [anhlm/Lop-10A01-Nhom-06#3]

**Comment by NguyenPhamThanhNgan** [comment]
+Gian nan có thuở thanh nhàn có khi : Câu ca dao nói về sự lạc quan, nhằm nhắn nhủ rằng cuộc sống đôi khi có khó khăn, có khi thuận lợi nhưng dù cuộc sống như thế nào chúng ta cũng nên sống lạc quan yêu đời để cuộc sống thêm đáng giá hơn. 
+Có khó mới có miếng ăn. Không dưng ai dễ đem phần đến cho : câu ca dao này đã khẳng định rằng chúng ta phải biết tự mình lao động, tự mình nỗ lực để nuôi sống chính mình, phải có làm thì mới có ăn. Thành quả lao động phải đến từ chính sự nỗ lực, chính bản thân mình chứ đừng nên dựa dẫm vào bất cứ ai khác.
+Khó mà biết lẽ biết lời. Biết ăn biết ở hơn người giàu sang : câu ca dao trên mang ý nghĩa sống là phải biết phải trái đúng sai, biết kính trên nhường dưới, tôn trọng mọi người thì mới được người khác đề cao, kính trọng.

**Comment by anhlm** [comment]
+ **Lời nói chẳng mất tiền mua, lựa lời mà nói cho vừa lòng nhau**: khi nói năng, giao tiếp với nhau thì nên thận trọng trong việc sử dụng ngôn ngữ. Lời lẽ trước khi thốt ra cần suy nghĩ kĩ tránh lỡ lời làm xúc phạm hay xấu đi mối quan hệ với mọi người xung quanh. Câu nói mang ý nghĩa khẳng định tầm quan trọng của lời nói đối với con người và khuyên ta nên thận trọng, suy nghĩ kĩ trước khi ăn nói.
+ **No ba ngày tết, đói ba tháng hè**: ám chỉ đến sự chi tiêu hoang phí trong những ngày tết và nhắc nhở ta rằng để có được cuộc sống no đủ ta nên biết cách chi tiêu hợp lí cũng như ngưng sắm sửa những thứ không cần thiết vào ngày tết. Ngày tết là ngày gia đình sum họp vui vẻ chứ không phải là nơi khoe khoang thế nên đừng chi quá nhiều cho những sự xa xỉ không cần thiết.

**Comment by theelphenomeno10** [comment]
Câu tục ngữ "Có công mài sắt có ngày nên kim." có 2 nghĩa: nghĩa đen và nghĩa bóng.
Nghĩa đen: Từ thanh sắt to có thể rèn thành một cây kim nhỏ bé.
Nghĩa bóng: Đức tính kiên trì trong cuộc sống.
